version: '3.8'
services:
  qoutex-bot:
    build: .
    container_name: qoutex_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./signals:/app/state
      - ./storageState.json:/app/storageState.json
      - ./signals_state.json:/app/signals_state.json
    network_mode: bridge
